services:
  app:
    image: $WORKSPACE_NAME/$APP_IMAGE
    build:
      context: $TPL_PATH/docker
      args:
        - BASE_IMAGE=$BASE_IMAGE
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
        - APP_NAME=$APP_NAME
        - SVC_PATH=$SVC_PATH
    hostname: "$APP_NAME.$BASE_DOMAIN"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
      VIRTUAL_PORT: "80"
      HOME: /tmp/home
    working_dir: /var/www
    entrypoint:
      - "/usr/local/bin/entrypoint"
    volumes:
      - "$SVC_PATH:/var/www"
      - "$HOME_PATH:/tmp/home"
      - "$HOME_PATH/.npm:/.npm"
      - "$HOME_PATH/.config:/.config"
      - "$PACKAGES_ROOT:$PACKAGES_ROOT"
      - "$TPL_PATH/docker/entrypoint:/usr/local/bin/entrypoint"
      - "$WORKSPACE_PATH/services/es/data:/var/data"
    networks:
      - dev
  nginx:
    image: $NGINX_IMAGE
    volumes:
      - "$SVC_PATH:/var/www"
      - "$TPL_PATH/nginx/default.conf.template:/etc/nginx/conf.d/default.conf"
    network_mode: "service:app"
    depends_on:
      - app

networks:
  dev:
    external: true
    name: $NETWORK