[package]
name = "uniform-cli-new"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0.0"
indexmap = {version = "1.9.1", features = ["serde-1"]}
lazy_static = "1.4.0"
regex = "1.8.1"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
structopt = "0.3.26"
prettytable-rs = "^0.10"
tokio = { version = "1.28.0", features = ["full"] }
futures = "0.3.28"

