#!/bin/ash

umask 0000

cd /app

if [ -e "container.env" ]; then
    variables=$(sed "s/^#.*//" "container.env")
    if [ "$variables" != "" ]; then
        export $variables
    fi
fi

# if [ ! -e /var/www/storage/ensi ] && [ -e /var/data ]; then
#     ln -s /var/data /var/www/storage/ensi
# fi

# if [ ! -L /var/www/public/storage ]; then
#     if [ -e vendor ]; then
#         echo "need to link storage!"
#         # php artisan storage:link
#     fi
# fi

SHELL=/bin/ash /usr/local/bin/npm run dev